BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE vendas CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN  -- ORA-00942: table or view does not exist
      RAISE;
    END IF;
END;
/